apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  labels:
    release: prometheus
spec:
  selector: 
    matchLabels:
      app.kubernetes.io/instance: redis-exporter
      app.kubernetes.io/name: prometheus-redis-exporter
  endpoints:
    - port: redis-exporter
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: postgres-exporter
  endpoints:
    - port: http
      interval: 30s
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-exporter
  labels:
    release: prometheus
spec:
  selector: 
    matchLabels:
      app: flask-app
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default