prometheus:
  prometheusSpec:
    # additionalScrapeConfigs: |
    #   - job_name: postgres-exporter
    #     static_configs:
    #       - targets:
    #         - postgres-exporter-prometheus-postgres-exporter:80
              
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
 
  
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
 
 
alertmanager:
  alertmanagerSpec:
    replicas: 1
 
 
grafana:
  enabled: true
  adminPassword: "admin"
 
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
 
 
kubeStateMetrics:
  enabled: true
 
nodeExporter:
  enabled: true
 
 
prometheusOperator:
  enabled: true
 
 
defaultRules:
  create: true